#!/usr/bin/python3
import sys

def tonum(s):
    try:
        ans += int(line)
    except:
        ans += float(line)
 
 ans = 0
 for line in sys.stdin:
     ans += tonum(line)

for line in sys.stdin:
    line = line.rstrip()

print(ans)
